[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "langchain>=0.3.27",
    "pinecone>=7.3.0",
    "python-dotenv>=1.1.1",
    "sentence-transformers>=5.1.0",
]
